name: flutter_super_badge
description: A native plugin to update the app badge count on the app icon.
version: 0.0.1
homepage: https://github.com/TesteurManiak/flutter_super_badge

environment:
  sdk: ">=3.1.5 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.maniak.flutter_super_badge
        pluginClass: FlutterSuperBadgePlugin
      ios:
        pluginClass: FlutterSuperBadgePlugin
