// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsMethodChannelMessages(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashMethodChannelMessages(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsMethodChannelMessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsMethodChannelMessages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsMethodChannelMessages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsMethodChannelMessages(lhsKey, rhsKey) {
          if deepEqualsMethodChannelMessages(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsMethodChannelMessages(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashMethodChannelMessages(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashMethodChannelMessages(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashMethodChannelMessages(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashMethodChannelMessages(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashMethodChannelMessages(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashMethodChannelMessages(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// Customization options for the notification displayed **on Android only**.
///
/// Generated class from Pigeon that represents data sent in messages.
struct AndroidBadgeSettings: Hashable {
  /// Callback used to localize the count string.
  ///
  /// Defaults to: "You have $count notification(s)"
  var message: String
  /// Specifies the icon to be used in the notification.
  var icon: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AndroidBadgeSettings? {
    let message = pigeonVar_list[0] as! String
    let icon: String? = nilOrValue(pigeonVar_list[1])

    return AndroidBadgeSettings(
      message: message,
      icon: icon
    )
  }
  func toList() -> [Any?] {
    return [
      message,
      icon,
    ]
  }
  static func == (lhs: AndroidBadgeSettings, rhs: AndroidBadgeSettings) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMethodChannelMessages(lhs.message, rhs.message) && deepEqualsMethodChannelMessages(lhs.icon, rhs.icon)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AndroidBadgeSettings")
    deepHashMethodChannelMessages(value: message, hasher: &hasher)
    deepHashMethodChannelMessages(value: icon, hasher: &hasher)
  }
}

private class MethodChannelMessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return AndroidBadgeSettings.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MethodChannelMessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? AndroidBadgeSettings {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MethodChannelMessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MethodChannelMessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MethodChannelMessagesPigeonCodecWriter(data: data)
  }
}

class MethodChannelMessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MethodChannelMessagesPigeonCodec(readerWriter: MethodChannelMessagesPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol FlutterSuperBadgeApi {
  func updateBadgeCount(count: Int64, settings: AndroidBadgeSettings) throws
  func removeBadge() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class FlutterSuperBadgeApiSetup {
  static var codec: FlutterStandardMessageCodec { MethodChannelMessagesPigeonCodec.shared }
  /// Sets up an instance of `FlutterSuperBadgeApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: FlutterSuperBadgeApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let updateBadgeCountChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_super_badge.FlutterSuperBadgeApi.updateBadgeCount\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateBadgeCountChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let countArg = args[0] as! Int64
        let settingsArg = args[1] as! AndroidBadgeSettings
        do {
          try api.updateBadgeCount(count: countArg, settings: settingsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateBadgeCountChannel.setMessageHandler(nil)
    }
    let removeBadgeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_super_badge.FlutterSuperBadgeApi.removeBadge\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeBadgeChannel.setMessageHandler { _, reply in
        do {
          try api.removeBadge()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      removeBadgeChannel.setMessageHandler(nil)
    }
  }
}
